//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishEducation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnglishEducationEntities : DbContext
    {
        public EnglishEducationEntities()
            : base("name=EnglishEducationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answer> Answer { get; set; }
        public DbSet<Lesson> Lesson { get; set; }
        public DbSet<LessonQuestion> LessonQuestion { get; set; }
        public DbSet<LessonVocabulary> LessonVocabulary { get; set; }
        public DbSet<Parameter> Parameter { get; set; }
        public DbSet<Question> Question { get; set; }
        public DbSet<Vocabulary> Vocabulary { get; set; }
    }
}
