//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public int ParamId { get; set; }
        public Nullable<int> ParamValue { get; set; }
        public string ParamType { get; set; }
        public string ParamDescription { get; set; }
    }
}
