//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVocabulary
    {
        public int VocabularyId { get; set; }
        public string EnglishWord { get; set; }
        public string TurkishWord { get; set; }
    }
}
